!obj:pylearn2.train.Train {
    dataset: &train !obj:emotiw.bouthilx.datasets.FeaturesDataset {
        features_paths: ["ActivityRecognition/activity_train_features.npy"],
        targets_path: "afew2_train_targets.npy",
        base_path: "/data/afew/ModelPredictionsToCombine/"
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: %(hid1)d,
                     sparse_init: 1
                  }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: %(hid2)d,
                     sparse_init: 1
                  },  !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h3',
                     dim: 35,
                     sparse_init: 1
                  },!obj:emotiw.bouthilx.models.LinearClassif {
                     layer_name: 'y',
                     dim: 7,
                     irange: 0.
                 }
                ],
       nvis: 3000,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 20,
        learning_rate: %(learning_rate)e,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:emotiw.bouthilx.datasets.FeaturesDataset {
                    features_paths: ["ActivityRecognition/activity_valid_features.npy"],
                    targets_path: "afew2_valid_targets.npy",
                    base_path: "/data/afew/ModelPredictionsToCombine/"
                },
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:emotiw.bouthilx.costs.MulticlassMargin { }, 
            !obj:pylearn2.models.mlp.WeightDecay {
                coeffs: [ %(wd1)f, %(wd2)f, %(wd3)f, %(wd4)f]
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 20
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
    ],
}
