!obj:pylearn2.train.Train {
    dataset: &train !obj:emotiw.bouthilx.datasets.FeaturesDataset {
        features_paths: ["audio/audio_mlp_train_feats_pca.npy",
                         "pascal/afew2_train_ramanan1_emmanuel_v2_features.npy"],
        targets_path: "pascal/afew2_train_ramanan1_emmanuel_v2_targets.npy",
        base_path: "/data/afew",
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.maxout.Maxout {
                     layer_name: 'h0',
                     num_units: 240,
                     num_pieces: 2,
                     irange: .005,
                     max_col_norm: 1.2365
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 7,
                     irange: .005,
                     max_col_norm: 1.9365
                 }
                ],
        nvis: 84,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 4,
        learning_rate: .001,
        init_momentum: .5,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:emotiw.bouthilx.datasets.FeaturesDataset {
                    features_paths: ["audio/audio_mlp_valid_feats_pca.npy",
                                     "pascal/afew2_valid_ramanan1_emmanuel_v2_features.npy"],
                    targets_path: "pascal/afew2_valid_ramanan1_emmanuel_v2_targets.npy",
                    base_path: "/data/afew",
                },
            },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 'h0' : .6 },
            input_scales: { 'h0': 1. }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 200
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.000004,
            min_lr: .000001
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7
        }
    ],
}
