!obj:pylearn2.train.Train {

    dataset: &train !obj:emotiw.bouthilx.datasets.AFEWDataset {
             base_path: '/data/afew/facetubes',
             which_set: 'train',
             start: 0,
             stop: 500,
    },

    model: !obj:pylearn2.models.mlp.MLP {
        layers : [

            !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h0',
                     output_channels: 64,
                     irange: .05,
                     kernel_shape: [5, 5],
                     pool_shape: [4, 4],
                     pool_stride: [3, 3],
                     max_kernel_norm: 1.9365,
                     border_mode: 'full'
            }, !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h4',
                     dim: 10,
                     sparse_init: 15,
            }, !obj:pylearn2.models.mlp.Softmax {
                layer_name: 'y',
                init_bias_target_marginals: *train,
                irange: .0,
                n_classes: 7
            }
        ],

        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [96, 96],
            num_channels: 3
        }

    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 64,
        learning_rate: .1,
#        init_momentum: .5,
        monitoring_dataset:
            {
                'trainsub' : !obj:emotiw.bouthilx.datasets.AFEWDataset {
                    base_path: '/data/afew/facetubes',
                    which_set: 'train',
                    start: 0,
                    stop: 100,
                },

                'valid' : !obj:emotiw.bouthilx.datasets.AFEWDataset {
                    base_path: '/data/afew/facetubes',
                    which_set: 'valid',
                    start: 0,
                    stop: 100,
                }
            },
            
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
    },

    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        }, !obj:emotiw.bouthilx.transform.SaveTransform {
             freq: 1,
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_examples"
        }, !obj:pylearn2.training_algorithms.sgd.OneOverEpoch {
             start: 15,
        }
    ],
}
