!obj:pylearn2.train.Train {
    dataset: &train !obj:emotiw.bouthilx.datasets.FeaturesDataset {
        features_paths: ["Audio/learned_on_train_predict_on_train_scores.npy",
                         "ConvNetPlusSVM_PierreSamiraChris/experiment_4/AFEW_train/prob_values_train.npy"],
        targets_path: "afew2_train_targets.npy",
        base_path: "/data/afew/ModelPredictionsToCombine",
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [ !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 140,
                     irange: 0.005
                  },!obj:emotiw.bouthilx.models.LinearClassif {
                     layer_name: 'y',
                     dim: 7,
                     irange: 0.005
                 }
                ],
        nvis: 14,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 10,
        learning_rate: 0.0001,
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:emotiw.bouthilx.datasets.FeaturesDataset {
                    features_paths: ["Audio/learned_on_train_predict_on_valid_scores.npy",
                                     "ConvNetPlusSVM_PierreSamiraChris/experiment_4/AFEW_validation/prob_values_val.npy"],
                    targets_path: "afew2_valid_targets.npy",
                    base_path: "/data/afew/ModelPredictionsToCombine",
                },
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:emotiw.bouthilx.costs.MulticlassMargin { }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 50
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
    ],
}
